name: ShowReminder
uuid: 30f3a2f1-aeca-4cef-b202-713caff486ca
subProjects:
    - name: ShowReminder.Web
      type: web
      packageManager: yarn
      webpack: true
      serviceName: showreminder-web
    - name: ShowReminder.Database
      type: database
      scriptDirectory: VersionedScripts
      versionPrefix: V
      versionSeparator: _
